import type {Config} from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-montserrat)', 'Montserrat', 'Inter', 'sans-serif'],
        serif: ['"Noto Serif"', 'serif'],
        display: ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        headline: ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        label: ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        'landing-display': ['var(--font-display)', 'sans-serif'],
        'landing-body': ['var(--font-body)', 'sans-serif'],
        cursive: ['"Meow Script"', 'cursive'],
        code: ['monospace'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        'on-surface': '#1F2937',
        'on-surface-variant': '#64748B',
        'outline-variant': '#CBD5E1',
        'surface-container': '#F1F5F9',
        'surface-container-low': '#F8FAFC',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#E2E8F0',
        'primary-fixed': '#E0E7FF',
        'primary-container': '#4F46E5',
        'on-primary-container': '#EEF2FF',
        'secondary-container': '#ECFCCB',
        'on-secondary-container': '#3F6212',
        'on-tertiary-container': '#9D174D',
        'landing-ink': 'var(--landing-ink)',
        'landing-ink-soft': 'var(--landing-ink-soft)',
        'landing-body': 'var(--landing-body)',
        'landing-muted': 'var(--landing-muted)',
        'landing-soft': 'rgba(21, 32, 35, 0.72)',
        'landing-faint': 'rgba(21, 32, 35, 0.4)',
        'landing-whisper': 'rgba(21, 32, 35, 0.3)',
        'landing-inverse': '#fbf8f2',
        'landing-inverse-soft': 'rgba(251, 248, 242, 0.74)',
        'landing-inverse-faint': 'rgba(251, 248, 242, 0.4)',
        'landing-teal': 'var(--landing-teal)',
        'landing-orange': 'var(--landing-orange)',
        'landing-neon': 'var(--landing-neon)',
        'landing-off-white': 'var(--off-white)',
        'landing-soft-border': 'rgba(21, 32, 35, 0.08)',
        'landing-muted-border': 'rgba(21, 32, 35, 0.12)',
        'landing-surface': 'rgba(255, 255, 255, 0.75)',
        'landing-surface-soft': 'rgba(255, 255, 255, 0.55)',
        'landing-subtle': 'rgba(21, 32, 35, 0.03)',
        'landing-subtle-strong': 'rgba(21, 32, 35, 0.05)',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '500' }],
        'label-xs': ['10px', { lineHeight: '1.0', letterSpacing: '0.6em', fontWeight: '400' }],
        'landing-eyebrow': ['10px', { lineHeight: '1.35', letterSpacing: '0.26em', fontWeight: '700' }],
        'landing-micro': ['11px', { lineHeight: '1.35', letterSpacing: '0.2em', fontWeight: '700' }],
        'landing-caption': ['11px', { lineHeight: '1.4', letterSpacing: '0.18em', fontWeight: '600' }],
      },
      spacing: {
        'margin-edge': '64px',
        'unit': '8px',
        'section-padding': '120px',
        'gutter': '24px',
        'margin': '32px',
        'sm-token': '12px',
        'xs-token': '4px',
        'lg-token': '48px',
        'xl-token': '80px',
        'md-token': '24px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        }
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      transitionTimingFunction: {
        'premium': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
