// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/booking/ai-concierge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/ai-concierge">> = Specific
  const handler = {} as typeof import("../../src/app/booking/ai-concierge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/booking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking">> = Specific
  const handler = {} as typeof import("../../src/app/booking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/booking/pre-session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/pre-session">> = Specific
  const handler = {} as typeof import("../../src/app/booking/pre-session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/book/details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/book/details">> = Specific
  const handler = {} as typeof import("../../src/app/client/book/details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/book">> = Specific
  const handler = {} as typeof import("../../src/app/client/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/client/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/fidelite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/fidelite">> = Specific
  const handler = {} as typeof import("../../src/app/client/fidelite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/client/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/login">> = Specific
  const handler = {} as typeof import("../../src/app/client/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/portal">> = Specific
  const handler = {} as typeof import("../../src/app/client/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profil">> = Specific
  const handler = {} as typeof import("../../src/app/client/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/clients">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/dashboard/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/dashboard/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/dashboard/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/magic-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/client/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/client">> = Specific
  const handler = {} as typeof import("../../src/app/client/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/therapist">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
